data:
  id: dlwh/wikitext_103_detokenized
model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "openwebtext", "gpt2"]

  mp: p=f32
  num_train_steps: 5000
  model_axis_size: 1
  per_device_parallelism: 1

  train_batch_size: 8

  checkpointer:
    keep:
      - every: 100
    save_interval: 5m

optimizer:
  learning_rate: 1E-3
  weight_decay: 0.1
  min_lr_ratio: 0.1
